#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveTheComic.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SaveComics")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLoaiTruyen(LoaiTruyen instance);
    partial void UpdateLoaiTruyen(LoaiTruyen instance);
    partial void DeleteLoaiTruyen(LoaiTruyen instance);
    partial void InsertTruyen(Truyen instance);
    partial void UpdateTruyen(Truyen instance);
    partial void DeleteTruyen(Truyen instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::SaveTheComic.Properties.Settings.Default.SaveComicsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LoaiTruyen> LoaiTruyens
		{
			get
			{
				return this.GetTable<LoaiTruyen>();
			}
		}
		
		public System.Data.Linq.Table<Truyen> Truyens
		{
			get
			{
				return this.GetTable<Truyen>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiTruyen")]
	public partial class LoaiTruyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maLoai;
		
		private string _tenLoai;
		
		private EntitySet<Truyen> _Truyens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLoaiChanging(int value);
    partial void OnmaLoaiChanged();
    partial void OntenLoaiChanging(string value);
    partial void OntenLoaiChanged();
    #endregion
		
		public LoaiTruyen()
		{
			this._Truyens = new EntitySet<Truyen>(new Action<Truyen>(this.attach_Truyens), new Action<Truyen>(this.detach_Truyens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maLoai
		{
			get
			{
				return this._maLoai;
			}
			set
			{
				if ((this._maLoai != value))
				{
					this.OnmaLoaiChanging(value);
					this.SendPropertyChanging();
					this._maLoai = value;
					this.SendPropertyChanged("maLoai");
					this.OnmaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLoai", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenLoai
		{
			get
			{
				return this._tenLoai;
			}
			set
			{
				if ((this._tenLoai != value))
				{
					this.OntenLoaiChanging(value);
					this.SendPropertyChanging();
					this._tenLoai = value;
					this.SendPropertyChanged("tenLoai");
					this.OntenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiTruyen_Truyen", Storage="_Truyens", ThisKey="maLoai", OtherKey="maLoai")]
		public EntitySet<Truyen> Truyens
		{
			get
			{
				return this._Truyens;
			}
			set
			{
				this._Truyens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Truyens(Truyen entity)
		{
			this.SendPropertyChanging();
			entity.LoaiTruyen = this;
		}
		
		private void detach_Truyens(Truyen entity)
		{
			this.SendPropertyChanging();
			entity.LoaiTruyen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Truyen")]
	public partial class Truyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maTruyen;
		
		private string _tenTruyen;
		
		private System.Nullable<int> _chap;
		
		private System.Nullable<int> _maLoai;
		
		private System.Nullable<System.DateTime> _ngayDocCuoi;
		
		private System.Data.Linq.Binary _img;
		
		private System.Nullable<bool> _hot;
		
		private System.Nullable<bool> _blackList;
		
		private string _noiDung;
		
		private EntityRef<LoaiTruyen> _LoaiTruyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaTruyenChanging(int value);
    partial void OnmaTruyenChanged();
    partial void OntenTruyenChanging(string value);
    partial void OntenTruyenChanged();
    partial void OnchapChanging(System.Nullable<int> value);
    partial void OnchapChanged();
    partial void OnmaLoaiChanging(System.Nullable<int> value);
    partial void OnmaLoaiChanged();
    partial void OnngayDocCuoiChanging(System.Nullable<System.DateTime> value);
    partial void OnngayDocCuoiChanged();
    partial void OnimgChanging(System.Data.Linq.Binary value);
    partial void OnimgChanged();
    partial void OnhotChanging(System.Nullable<bool> value);
    partial void OnhotChanged();
    partial void OnblackListChanging(System.Nullable<bool> value);
    partial void OnblackListChanged();
    partial void OnnoiDungChanging(string value);
    partial void OnnoiDungChanged();
    #endregion
		
		public Truyen()
		{
			this._LoaiTruyen = default(EntityRef<LoaiTruyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maTruyen", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maTruyen
		{
			get
			{
				return this._maTruyen;
			}
			set
			{
				if ((this._maTruyen != value))
				{
					this.OnmaTruyenChanging(value);
					this.SendPropertyChanging();
					this._maTruyen = value;
					this.SendPropertyChanged("maTruyen");
					this.OnmaTruyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenTruyen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenTruyen
		{
			get
			{
				return this._tenTruyen;
			}
			set
			{
				if ((this._tenTruyen != value))
				{
					this.OntenTruyenChanging(value);
					this.SendPropertyChanging();
					this._tenTruyen = value;
					this.SendPropertyChanged("tenTruyen");
					this.OntenTruyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chap", DbType="Int")]
		public System.Nullable<int> chap
		{
			get
			{
				return this._chap;
			}
			set
			{
				if ((this._chap != value))
				{
					this.OnchapChanging(value);
					this.SendPropertyChanging();
					this._chap = value;
					this.SendPropertyChanged("chap");
					this.OnchapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai", DbType="Int")]
		public System.Nullable<int> maLoai
		{
			get
			{
				return this._maLoai;
			}
			set
			{
				if ((this._maLoai != value))
				{
					if (this._LoaiTruyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLoaiChanging(value);
					this.SendPropertyChanging();
					this._maLoai = value;
					this.SendPropertyChanged("maLoai");
					this.OnmaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayDocCuoi", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayDocCuoi
		{
			get
			{
				return this._ngayDocCuoi;
			}
			set
			{
				if ((this._ngayDocCuoi != value))
				{
					this.OnngayDocCuoiChanging(value);
					this.SendPropertyChanging();
					this._ngayDocCuoi = value;
					this.SendPropertyChanged("ngayDocCuoi");
					this.OnngayDocCuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this.OnimgChanging(value);
					this.SendPropertyChanging();
					this._img = value;
					this.SendPropertyChanged("img");
					this.OnimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hot", DbType="Bit")]
		public System.Nullable<bool> hot
		{
			get
			{
				return this._hot;
			}
			set
			{
				if ((this._hot != value))
				{
					this.OnhotChanging(value);
					this.SendPropertyChanging();
					this._hot = value;
					this.SendPropertyChanged("hot");
					this.OnhotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_blackList", DbType="Bit")]
		public System.Nullable<bool> blackList
		{
			get
			{
				return this._blackList;
			}
			set
			{
				if ((this._blackList != value))
				{
					this.OnblackListChanging(value);
					this.SendPropertyChanging();
					this._blackList = value;
					this.SendPropertyChanged("blackList");
					this.OnblackListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiDung", DbType="NVarChar(200)")]
		public string noiDung
		{
			get
			{
				return this._noiDung;
			}
			set
			{
				if ((this._noiDung != value))
				{
					this.OnnoiDungChanging(value);
					this.SendPropertyChanging();
					this._noiDung = value;
					this.SendPropertyChanged("noiDung");
					this.OnnoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiTruyen_Truyen", Storage="_LoaiTruyen", ThisKey="maLoai", OtherKey="maLoai", IsForeignKey=true)]
		public LoaiTruyen LoaiTruyen
		{
			get
			{
				return this._LoaiTruyen.Entity;
			}
			set
			{
				LoaiTruyen previousValue = this._LoaiTruyen.Entity;
				if (((previousValue != value) 
							|| (this._LoaiTruyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiTruyen.Entity = null;
						previousValue.Truyens.Remove(this);
					}
					this._LoaiTruyen.Entity = value;
					if ((value != null))
					{
						value.Truyens.Add(this);
						this._maLoai = value.maLoai;
					}
					else
					{
						this._maLoai = default(Nullable<int>);
					}
					this.SendPropertyChanged("LoaiTruyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
